# Generated by Django 3.0.7 on 2020-07-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20200705_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describtion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('usersinfo', models.ManyToManyField(to='accounts.Info')),
            ],
        ),
    ]
