# Generated by Django 3.0.7 on 2020-07-02 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_upgraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgraderequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upgraderequest',
            name='dream_role',
            field=models.CharField(choices=[('EO', 'Employee of an organization'), ('DO', 'Director of an organization')], max_length=2),
        ),
    ]
