# Generated by Django 3.0.7 on 2020-07-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_info_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='role',
            field=models.CharField(choices=[('EE', 'Employee'), ('EO', 'Employee of an organization'), ('DO', 'Director of an organization')], default='EE', max_length=2),
        ),
    ]
